name: Automated Release Deployment

on:
  push:
    branches:
      - main
      - 'feature/deploy'
  
  env:
    NODE_VERSION: 16.17.1
    IP_ADDRESS: "49.12.188.8"

  jobs:
    test-application:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Test Application
          uses: actions/setup-node@v3
          with:
            node-version: 16.17.1
            cache: 'yarn'
        - run : |
           yarn
           yarn build
           yarn test
